services:
  mongo:
    image: mongo:6
    container_name: snaplink-mongo
    restart: unless-stopped

    expose:
      - "27017"

    volumes:
      - snaplink-mongo-data:/data/db

    healthcheck:
      test:
        ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - snaplink-network

  redis:
    image: redis:7-alpine
    container_name: snaplink-redis
    restart: unless-stopped

    expose:
      - "6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

    networks:
      - snaplink-network

  backend:
    image: ghcr.io/anwarbuilds1/snaplink-backend:latest

    container_name: snaplink-backend

    restart: unless-stopped

    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy

    env_file:
      - ./backend/.env

    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo:27017/url-shortener
      REDIS_URL: redis://redis:6379
      BASE_URL: https://snaplink.anwarbuilds.com

    ports:
      - "127.0.0.1:5000:5000"

    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--spider",
          "--quiet",
          "http://localhost:5000/system/health",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

    networks:
      - snaplink-network

  frontend:
    image: ghcr.io/anwarbuilds1/snaplink-frontend:latest

    container_name: snaplink-frontend

    restart: unless-stopped

    depends_on:
      backend:
        condition: service_healthy

    ports:
      - "127.0.0.1:5173:80"

    networks:
      - snaplink-network

volumes:
  snaplink-mongo-data:

networks:
  snaplink-network:
    driver: bridge
